### ISSUE TITLE
把 tj 去掉，别恶心人了在那

### ISSUE THREAD

**Issue by abrahamgreyson** [Meizhuo/silentor#12]
Such an annoying behavior,  do not interrupt other people.

**Comment by overtrue** [comment]
这种行为真可耻，要宣传项目就去开源中国，去各大社区，这种行为只能是丢国人脸。

![image](https://cloud.githubusercontent.com/assets/1472352/15168057/75ac970a-1760-11e6-9f0c-2ffd65a28ffb.png)

**Comment by lonquan** [comment]
药店碧莲.....

**Comment by jcc** [comment]
stupid。

**Comment by HavenShen** [comment]
被 恶心到了。

**Comment by Zhengbledore** [comment]
药店碧莲.....

**Comment by caikeal** [comment]
恶心

**Comment by sqrtqiezi** [comment]
分享个真实事情：某新修道路一直没装监控，过往车辆习惯性超速，后来交警装了监控，一抓一大票。
少点套路多点真诚，习惯性占便宜，一定会掉坑里，而且没人会搭理你

**Comment by overtrue** [comment]
@sqrtqiezi 💯

**Comment by skyhacker2** [comment]
tj都没说什么，吐槽个毛？

**Comment by jacsonLee** [comment]
tj 都不说话 你们瞎逼逼个毛啊 ！🚀

**Comment by jianzhiyao** [comment]
不知道一堆人紧张啥，tj看得上就看得上，看不上就看不上。又不是日了你们家老母猪

**Comment by GingJan** [comment]
瞎逼逼啥啊，tj又没出声

**Comment by overtrue** [comment]
@skyhacker2 @jacsonLee @jianzhiyao @zjien 

你们是假装不知道还是揣着明白装糊涂？它的这个行为，让 tj 2万多关注者的 feed 都收到了下图的通知：

![image](https://cloud.githubusercontent.com/assets/1472352/15168057/75ac970a-1760-11e6-9f0c-2ffd65a28ffb.png)

明白了没？这是骚扰！

**Comment by bangzhuhao** [comment]
瞎逼逼个毛，tj都无出声

**Comment by abrahamgreyson** [comment]
@overtrue 
@skyhacker2 @jacsonLee @jianzhiyao @zjien @bangzhuhao
哈哈，看他们几个主页模版都一样样的，估计和你那粉丝一样，都是同学。
真的挺毁三观的，这种通过圈大神去骚扰他关注者的行为非常浪费别人时间。
把时间用来完善东西，做些有用的事岂不是更好？同学们怎么就不明白呢，一忽悠就全来帮洗？

**Comment by overtrue** [comment]
@abrahamgreyson 呵呵，取消订阅这条 issue 吧，让他们继续用这样的恶行丢国内脸吧，反正他们也不在乎，有句话说得好：你叫不醒装睡的人。好像还是一群学生，张口就脏话连篇，也许他们随时都把母亲带在身边吧。罢了，他们开心就好。祝好

![image](https://cloud.githubusercontent.com/assets/1472352/15169290/4498c830-176c-11e6-9cad-034f43724342.png)

**Comment by abrahamgreyson** [comment]
OK.

------------------ 原始邮件 ------------------
发件人: "安正超";notifications@github.com;
发送时间: 2016年5月11日(星期三) 中午11:36
收件人: "Meizhuo/silentor"silentor@noreply.github.com; 
抄送: "abraham greyson"82011220@qq.com; "Mention"mention@noreply.github.com; 
主题: Re: [Meizhuo/silentor] 把 tj 去掉，别恶心人了在那 (#12)

@abrahamgreyson 呵呵，取消订阅这条 issue 吧，让他们继续用这样的恶行丢国内脸吧，反正他们也不在乎，有句话说得好：你叫不醒装睡的人。好像还是一群学生，张口就脏话连篇，也许他们随时都把母亲带在身边吧。罢了，他们开心就好。祝好

**Comment by github-policemen** [comment]
@skyhacker2 @jacsonLee @zjien @bangzhuhao 

首先你们怎么知道 TJ 没有表态？你们都瞎吗？

@jianzhiyao 他当然看不上，他可能中文文档都看不懂，而且这个功能难道不是大家商量好了再邀请加入吗

---

Twitter: https://twitter.com/tjholowaychuk/status/714856883475976192

Github: https://github.com/719Ben/notice-me/issues/7

---

<img width="628" alt="2016-05-11 11 49 24" src="https://cloud.githubusercontent.com/assets/19298417/15169526/a3b1a236-176e-11e6-833d-67a1e9497345.png">

**Comment by fritx** [comment]
sorry, tj :joy:

**Comment by Jayin** [comment]
@fritx 下次注意一下
